version: 0.0.1
name: franquette-sql
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: bdd
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db/sql:/var/lib/mysql
    networks:
      - franquette-network
    ports:
      - 33060:3306
networks:
  franquette-network:
    driver: bridge
volumes:
  franquette-sql-data: