name: franquette-db
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: franquette-bdd
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ~/.docker/volumes/franquette/db/data:/var/lib/mysql:rw
    user: mysql
    ports:
      - 33060:3306