name: franquette-db
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: franquette-bdd
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ~/.docker/volumes/franquette/db/sql:/var/lib/mysql
    ports:
      - 33060:3306
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mdb
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - ~/.docker/volumes/franquette/db/mongo:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 33061:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mdb
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://mdb:test@mongo:27017/
      ME_CONFIG_BASICAUTH: false